[2025-02-17T11:10:56.894+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-17T11:10:57.479+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_operator_dag.task1 scheduled__2025-02-15T21:33:00+00:00 [queued]>
[2025-02-17T11:10:57.745+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_operator_dag.task1 scheduled__2025-02-15T21:33:00+00:00 [queued]>
[2025-02-17T11:10:57.962+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-17T11:10:58.523+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task1> on 2025-02-15 21:33:00+00:00
[2025-02-17T11:10:58.604+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=6685) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-17T11:10:58.674+0000] {standard_task_runner.py:72} INFO - Started process 6699 to run task
[2025-02-17T11:10:58.762+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'run_operator_dag', 'task1', 'scheduled__2025-02-15T21:33:00+00:00', '--job-id', '896', '--raw', '--subdir', 'DAGS_FOLDER/10_run_operator_dag.py', '--cfg-path', '/tmp/tmpzeicalvt']
[2025-02-17T11:10:59.083+0000] {standard_task_runner.py:105} INFO - Job 896: Subtask task1
[2025-02-17T11:11:00.767+0000] {task_command.py:467} INFO - Running <TaskInstance: run_operator_dag.task1 scheduled__2025-02-15T21:33:00+00:00 [running]> on host ab74d4d90d32
[2025-02-17T11:11:04.096+0000] {job.py:229} INFO - Heartbeat recovered after 35.77 seconds
[2025-02-17T11:11:04.741+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_operator_dag' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2025-02-15T21:33:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-15T21:33:00+00:00'
[2025-02-17T11:11:04.742+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-17T11:11:06.153+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-17T11:11:06.156+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'sleep 5']
[2025-02-17T11:11:07.099+0000] {subprocess.py:99} INFO - Output:
[2025-02-17T11:11:12.589+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-17T11:11:12.697+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-17T11:11:12.698+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=run_operator_dag, task_id=task1, run_id=scheduled__2025-02-15T21:33:00+00:00, execution_date=20250215T213300, start_date=20250217T111057, end_date=20250217T111112
[2025-02-17T11:11:12.847+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-17T11:11:12.937+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-17T11:11:12.953+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
