[2025-02-17T21:33:07.148+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-17T21:33:07.173+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_all_failed_dag.task3 scheduled__2025-02-16T21:33:00+00:00 [queued]>
[2025-02-17T21:33:07.186+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_all_failed_dag.task3 scheduled__2025-02-16T21:33:00+00:00 [queued]>
[2025-02-17T21:33:07.186+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-17T21:33:07.199+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task3> on 2025-02-16 21:33:00+00:00
[2025-02-17T21:33:07.203+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=8063) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-17T21:33:07.205+0000] {standard_task_runner.py:72} INFO - Started process 8064 to run task
[2025-02-17T21:33:07.205+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'trigger_all_failed_dag', 'task3', 'scheduled__2025-02-16T21:33:00+00:00', '--job-id', '959', '--raw', '--subdir', 'DAGS_FOLDER/07_trigger_all_failed_dag.py', '--cfg-path', '/tmp/tmp2d4r620g']
[2025-02-17T21:33:07.206+0000] {standard_task_runner.py:105} INFO - Job 959: Subtask task3
[2025-02-17T21:33:07.251+0000] {task_command.py:467} INFO - Running <TaskInstance: trigger_all_failed_dag.task3 scheduled__2025-02-16T21:33:00+00:00 [running]> on host ab74d4d90d32
[2025-02-17T21:33:07.339+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trigger_all_failed_dag' AIRFLOW_CTX_TASK_ID='task3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-16T21:33:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-16T21:33:00+00:00'
[2025-02-17T21:33:07.340+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-17T21:33:07.354+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-17T21:33:07.355+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'sleep 5']
[2025-02-17T21:33:07.362+0000] {subprocess.py:99} INFO - Output:
[2025-02-17T21:33:12.375+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-17T21:33:12.461+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-17T21:33:12.462+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=trigger_all_failed_dag, task_id=task3, run_id=scheduled__2025-02-16T21:33:00+00:00, execution_date=20250216T213300, start_date=20250217T213307, end_date=20250217T213312
[2025-02-17T21:33:12.646+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-17T21:33:12.728+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-17T21:33:12.739+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
