[2025-02-14T21:39:29.897+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T21:39:29.920+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: call_run_operator_dag.run_dag_task manual__2025-02-14T21:39:22.078640+00:00 [queued]>
[2025-02-14T21:39:29.930+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: call_run_operator_dag.run_dag_task manual__2025-02-14T21:39:22.078640+00:00 [queued]>
[2025-02-14T21:39:29.931+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-14T21:39:29.945+0000] {taskinstance.py:2890} INFO - Executing <Task(TriggerDagRunOperator): run_dag_task> on 2025-02-14 21:39:22.078640+00:00
[2025-02-14T21:39:29.949+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=879) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-14T21:39:29.952+0000] {standard_task_runner.py:72} INFO - Started process 880 to run task
[2025-02-14T21:39:29.951+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'call_run_operator_dag', 'run_dag_task', 'manual__2025-02-14T21:39:22.078640+00:00', '--job-id', '858', '--raw', '--subdir', 'DAGS_FOLDER/11_run_operator_dag.py', '--cfg-path', '/tmp/tmpsh86wnem']
[2025-02-14T21:39:29.953+0000] {standard_task_runner.py:105} INFO - Job 858: Subtask run_dag_task
[2025-02-14T21:39:30.006+0000] {task_command.py:467} INFO - Running <TaskInstance: call_run_operator_dag.run_dag_task manual__2025-02-14T21:39:22.078640+00:00 [running]> on host ab74d4d90d32
[2025-02-14T21:39:30.128+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='call_run_operator_dag' AIRFLOW_CTX_TASK_ID='run_dag_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T21:39:22.078640+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-14T21:39:22.078640+00:00'
[2025-02-14T21:39:30.129+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-14T21:39:30.250+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-14T21:39:30.251+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=call_run_operator_dag, task_id=run_dag_task, run_id=manual__2025-02-14T21:39:22.078640+00:00, execution_date=20250214T213922, start_date=20250214T213929, end_date=20250214T213930
[2025-02-14T21:39:30.328+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-14T21:39:30.348+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-14T21:39:30.350+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
