[2025-02-16T13:22:04.663+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-16T13:22:04.974+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: group_task_dag.task1 scheduled__2025-02-14T21:33:00+00:00 [queued]>
[2025-02-16T13:22:05.416+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: group_task_dag.task1 scheduled__2025-02-14T21:33:00+00:00 [queued]>
[2025-02-16T13:22:05.427+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-16T13:22:07.450+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task1> on 2025-02-14 21:33:00+00:00
[2025-02-16T13:22:07.471+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5319) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-16T13:22:07.474+0000] {standard_task_runner.py:72} INFO - Started process 5342 to run task
[2025-02-16T13:22:07.861+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'group_task_dag', 'task1', 'scheduled__2025-02-14T21:33:00+00:00', '--job-id', '868', '--raw', '--subdir', 'DAGS_FOLDER/09_group_task_dag.py', '--cfg-path', '/tmp/tmp73xy1bkj']
[2025-02-16T13:22:08.095+0000] {standard_task_runner.py:105} INFO - Job 868: Subtask task1
[2025-02-16T13:22:10.057+0000] {task_command.py:467} INFO - Running <TaskInstance: group_task_dag.task1 scheduled__2025-02-14T21:33:00+00:00 [running]> on host ab74d4d90d32
[2025-02-16T13:22:16.213+0000] {job.py:229} INFO - Heartbeat recovered after 13.04 seconds
[2025-02-16T13:22:17.323+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='group_task_dag' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T21:33:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-14T21:33:00+00:00'
[2025-02-16T13:22:17.394+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-16T13:22:18.381+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-16T13:22:18.383+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'sleep 5']
[2025-02-16T13:22:18.731+0000] {subprocess.py:99} INFO - Output:
[2025-02-16T13:22:23.745+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-16T13:22:24.146+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-16T13:22:24.147+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=group_task_dag, task_id=task1, run_id=scheduled__2025-02-14T21:33:00+00:00, execution_date=20250214T213300, start_date=20250216T132204, end_date=20250216T132224
[2025-02-16T13:22:24.819+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-16T13:22:25.702+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-02-16T13:22:26.347+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-16T13:22:26.379+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
